// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onHumChange();
void onTempChange();
void onAlarmstateChange();

float hum;
float temp;
bool alarmstate;

void initProperties(){

  ArduinoCloud.addProperty(hum, READWRITE, ON_CHANGE, onHumChange);
  ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange);
  ArduinoCloud.addProperty(alarmstate, READWRITE, ON_CHANGE, onAlarmstateChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
